import './globals.css'
import type { Metadata } from 'next'
import { Analytics } from '@vercel/analytics/react'
import RootStyleRegistry from './emotion'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <title>youtubify</title>
      </head>
      <body>
        <RootStyleRegistry>{children}</RootStyleRegistry>
        <Analytics />
      </body>
    </html>
  )
}
